[package]
name = "lzokay"
version = "2.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/encounter/lzokay-rs"
documentation = "https://docs.rs/lzokay"
readme = "README.md"
description = """
A minimal, MIT-licensed implementation of the LZO compression format.
"""
keywords = ["lzo", "compression", "no_std"]
categories = ["compression", "no-std", "api-bindings"]
rust-version = "1.81.0"

[features]
alloc = []
std = ["alloc"]
decompress = []
compress = []
default = ["compress", "decompress", "std"]
