name: build

on: [ push, pull_request ]

jobs:
  default:
    name: Default
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable, 1.70.0, nightly ]
        features:
            - compress,alloc
            - compress,decompress
            - compress,decompress,std
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@v1
        if: matrix.platform == 'windows-latest'
        with:
          version: 21.1.2
          directory: ${{ runner.temp }}/llvm
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: matrix.platform == 'windows-latest'
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-default-features --features ${{ matrix.features }}
