name: Python Package

on:
  push:
    branches:
      - main
    tags:
      - "*"

  pull_request:
    branches:
      - main

jobs:
  build-sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - name: Store the packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-source
          path: dist

  build-wheels:
    name: Build ${{ matrix.platform }} wheels (${{ matrix.archs }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            archs: x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            platform: linux
            archs: i686
            target: i686-unknown-linux-gnu
          - os: macos-latest
            platform: macos
            archs: universal2
            target: x86_64-apple-darwin
          - os: windows-latest
            platform: windows
            archs: AMD64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            platform: windows
            archs: x86
            target: i686-pc-windows-msvc
          - os: windows-latest
            platform: windows
            archs: ARM64
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.target }}
        if: matrix.target != ''

      - uses: pypa/cibuildwheel@v3.2.1
        with:
          output-dir: dist
        env:
          CIBW_ARCHS: ${{ matrix.archs }}
          CIBW_TEST_EXTRAS: test
          CIBW_TEST_COMMAND: pytest {project}/python/tests
          MACOSX_DEPLOYMENT_TARGET: "10.12"

      - name: codecov
        uses: codecov/codecov-action@v5

      - name: Store the packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ matrix.only }}
          path: dist

  pypi:
    runs-on: ubuntu-latest
    needs:
      - build-sdist
      - build-wheels

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v5
        with:
          pattern: python-package-*
          merge-multiple: true
          path: dist/

      - name: Publish 📦 to TestPyPI
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish 📦 to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
